spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Warscat521
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx92bce8a900fc74bb
  mpAppSecret: 5273f2b276530e26f3950954db42d6eb
  openAppId: wx92bce8a900fc74bb
  openAppSecret: 5273f2b276530e26f3950954db42d6eb
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://y39qa4.natappfree.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://y39qa4.natappfree.cc
  wechatOpenAuthorize: http://y39qa4.natappfree.cc
  sell: http://y39qa4.natappfree.cc
