spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Warscat
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 5273f2b276530e26f3950954db42d6eb
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://wars.natapp1.cc/sell/pay/notify
  openAppId: wx92bce8a900fc74bb
  openAppSecret: 5273f2b276530e26f3950954db42d6eb
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://wars.natapp1.cc
  wechatOpenAuthorize: http://wars.natapp1.cc
  sell: http://wars.natapp1.cc
